"""
Wave.py — Wave manager; spawns enemies and tracks completion.
"""

import random # usado para spawnar inimigos em posições aleatórias e para variar o tempo de disparo e o ângulo inicial do padrão de tiro

from shared.Constants import (
    ENEMIES_PER_WAVE_BASE, ENEMIES_PER_WAVE_SCALE,
    ENEMY_BASE_HP, SCREEN_WIDTH, SCREEN_HEIGHT,
) # usado para definir o número de inimigos por onda, a escala de dificuldade e os limites da arena
from server.Enemy import Enemy # usado para criar e atualizar os inimigos em cada onda


class WaveManager:
    """
    Manages wave progression:
      WAITING  → players are in shop / pregame
      ACTIVE   → enemies are alive
      CLEARING → wave just cleared
    """

    TOTAL_WAVES = 10 

    def __init__(self):
        self.wave_number = 0
        self.enemies: list[Enemy] = []
        self.state = "WAITING"      # WAITING | ACTIVE | CLEARING

    def start_next_wave(self) -> None:
        self.wave_number += 1
        count = ENEMIES_PER_WAVE_BASE + (self.wave_number - 1) * ENEMIES_PER_WAVE_SCALE
        hp = ENEMY_BASE_HP + (self.wave_number - 1) * 20
        self.enemies = self._spawn_enemies(count, hp)
        self.state = "ACTIVE"

    def update(self, dt: float, players: list, now: float) -> list:
        """Returns new bullets generated by enemies this tick."""
        if self.state != "ACTIVE":
            return []

        new_bullets = []
        for enemy in self.enemies:
            if enemy.alive:
                new_bullets += enemy.update(dt, players, now)

        return new_bullets

    def all_dead(self) -> bool:
        for e in self.enemies:
            if e.alive:
                return False
            
        return self.state == "ACTIVE"
        
    def is_final_wave(self) -> bool:
        return self.wave_number >= self.TOTAL_WAVES

    def mark_clearing(self) -> None:
        self.state = "CLEARING"

    def mark_waiting(self) -> None:
        self.state = "WAITING"

    def living_enemies(self) -> list[Enemy]:
        enemies = []
        for e in self.enemies:
            if e.alive:
                enemies.append(e)
        return enemies

    def _spawn_enemies(self, count: int, hp: int) -> list[Enemy]:
        enemies = []
        margin = 80
        sides = ["top", "bottom", "left", "right"]
        for _ in range(count):
            # Spawn along arena border to keep arena clear
            side = sides[random.randint(0, 3)]
            if side == "top":
                x = random.randint(margin, SCREEN_WIDTH  - margin)
                y = margin
            elif side == "bottom":
                x = random.randint(margin, SCREEN_WIDTH  - margin)
                y = SCREEN_HEIGHT - margin
            elif side == "left": 
                x = margin
                y = random.randint(margin, SCREEN_HEIGHT - margin)
            elif side == "right":
                x = SCREEN_WIDTH - margin
                y = random.randint(margin, SCREEN_HEIGHT - margin)
            enemies.append(Enemy(x, y, hp, self.wave_number))
        return enemies

    # ── Serialization ─────────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        enemies = []
        for e in self.enemies:
            if e.alive:
                enemies.append(e.to_dict())
        return {
            "wave_number": self.wave_number,
            "state": self.state,
            "enemies": enemies,
        }