"""Shared constants for server and client."""

# Network
SERVER_HOST = "127.0.0.1"
SERVER_PORT = 5555

# Game
SCREEN_WIDTH = 1366
SCREEN_HEIGHT = 768
FPS = 60
TICK_RATE = 30  

MAX_PLAYERS = 7

# Player base stats
BASE_HP = 100
BASE_MANA = 100
BASE_SPEED = 220  # pixels per second
DASH_SPEED = 600
DASH_DURATION = 0.18  # seconds
DASH_COOLDOWN = 1.2   # seconds
BULLET_SPEED = 500
PLAYER_BULLET_DAMAGE = 10
PLAYER_RADIUS = 18

# Enemy
ENEMY_RADIUS = 22
ENEMY_BASE_HP = 60
ENEMY_SPEED = 80
ENEMY_BULLET_SPEED = 260
ENEMY_BULLET_DAMAGE = 12
ENEMY_COIN_REWARD = 5

# Wave
ENEMIES_PER_WAVE_BASE = 6
ENEMIES_PER_WAVE_SCALE = 3  # added per wave

# Shop upgrade costs
UPGRADE_DAMAGE_COST = 15
UPGRADE_HP_COST = 15
UPGRADE_MANA_COST = 15
UPGRADE_DAMAGE_AMOUNT = 5
UPGRADE_HP_AMOUNT = 20
UPGRADE_MANA_AMOUNT = 25